#!/bin/bash
#
# Recursively format all source files in src and test.
#
# Note that any files or directories that are excluded here should also be
# added to the 'exclude' list in .github/workflows/clang-format-check.yml

COMMAND="clang-format"

if [ $# -eq 1 ]; then
    COMMAND="$COMMAND-$1"
fi

echo ""
echo "format_source <version>"
echo ""
echo "Format the HDFView Java source using clang-format. The <version>"
echo "parameter is optional and can be used to force a specific"
echo "installed version of clang-format to be used."
echo ""

find . \( -type d -path ./src -and -path ./test \) \
    -or \( -iname *.java \) \
    | xargs -P0 -n1 ${COMMAND} -style=file -i -fallback-style=none

exit 0
